# -*- coding: utf-8 -*-
"""BerTopic

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1op7a3ORoCrS_BCkQURBTNpXDLeOUPf5A
"""

from bertopic import BERTopic

class BERTopicModel:
    def __init__(self):
        self.model = BERTopic()
        self.topics = None

    def train(self, documents):
        # Train the BERTopic model
        self.topics, _ = self.model.fit_transform(documents)

    def get_topics(self):
        if self.topics is None:
            raise ValueError("Model not trained. Call the train() method first.")

        return self.model.get_topic_info()

